routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', 'FrontendController@main')->name('mainpage');

Route::get('itemdetail/{id}', 'FrontendController@itemdetail')->name('itemdetail')->middleware('auth');

Route::get('cart', 'FrontendController@cart')->name('cartpage');

Route::get('signin','FrontendController@signin')->name('signinpage');

Route::get('signup','FrontendController@signup')->name('signuppage');

Route::middleware('role:admin')->group(function () {
	// backend
	Route::resource('brands', 'BrandController');
	Route::resource('categories', 'CategoryController');
	Route::resource('subcategories', 'SubcategoryController');
	Route::resource('items', 'ItemController');
});
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('orders','OrderController');

app/Item.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Item extends Model
{
  protected $fillable=['codeno', 'name', 'photo', 'price', 'discount', 'description', 'brand_id','subcategory_id'];

  public function brand()
  {
    return $this->belongsTo('App\Brand');
  }

  public function subcategory()
  {
    return $this->belongsTo('App\Subcategory');
  }

  public function orders($value='')
  {
    return $this->belongsToMany('App\Order','orderdetail')
                ->withPivot('qty')
                ->withTimestamps();         
  }
}

app/Http/Controllers/ItemController.php
<?php

namespace App\Http\Controllers;
use App\Brand;
use App\Subcategory;
use App\Item;
use Illuminate\Http\Request;

class ItemController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $item = Item::all();
        return view('backend.item.index',compact('item'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $brand = Brand::all();
        $subcategory = Subcategory::all();
        return view('backend.item.create',compact('brand','subcategory'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            "codeno" => '',
            "name" => 'required',
            "photo" => "required|mimes:jpeg,bmp,png", // a.jpg
            "price" => 'required',
            "discount" => '',
            "description" => 'required',
            "brand_id" => 'required',
            "subcategory_id" => 'required', 
        ],[
            "name.required" => "Pleace Enter Item Name"
        ]);
        // If include file, upload
        if($request->file()) {
            // 624872374523_a.jpg
            $fileName = time().'_'.$request->photo->getClientOriginalName();
            // itemimg/624872374523_a.jpg
            $filePath = $request->file('photo')->storeAs('itemimg', $fileName, 'public');
            $path = '/storage/'.$filePath;
        }
        // Object Relational Mapping (Eloquent ORM)
        $item = new Item;
        $item->codeno = uniqid();
        $item->name = $request->name;
        $item->photo = $path;
        $item->price = $request->price;
        $item->discount = $request->discount;
        $item->description = $request->description;
        $item->brand_id = $request->brand_id;
        $item->subcategory_id = $request->subcategory_id;
        $item->save();
        return redirect()->route('items.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function show(Item $item)
    {
        $brand = Brand::all();
        $subcategory = Subcategory::all();
        return view('backend.item.show',compact('item','brand','subcategory'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function edit(Item $item)
    {
        $brand = Brand::all();
        $subcategory = Subcategory::all();
        return view('backend.item.edit',compact('item','brand','subcategory'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Item $item)
    {
        $request->validate([
            "codeno" => '',
            "name" => 'required',
            "photo" => "required|mimes:jpeg,bmp,png", // a.jpg
            "price" => 'required',
            "discount" => '',
            "description" => 'required',
            "brand_id" => 'required',
            "subcategory_id" => 'required', 
        ],[
            "name.required" => "Pleace Enter Item Name"
        ]);
        // If include file, upload
        if($request->file()) {
            // 624872374523_a.jpg
            $fileName = time().'_'.$request->photo->getClientOriginalName();
            // itemimg/624872374523_a.jpg
            $filePath = $request->file('photo')->storeAs('itemimg', $fileName, 'public');
            $path = '/storage/'.$filePath;
        }
        // Object Relational Mapping (Eloquent ORM)
        $item->codeno = uniqid();
        $item->name = $request->name;
        $item->photo = $path;
        $item->price = $request->price;
        $item->discount = $request->discount;
        $item->description = $request->description;
        $item->brand_id = $request->brand_id;
        $item->subcategory_id = $request->subcategory_id;
        $item->save();
        return redirect()->route('items.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function destroy(Item $item)
    {
        $item->delete();
        return redirect()->route('items.index');
    }
}

resources/views/backend/item/create.blade.php
@extends('backendtemplate')

@section('content')
  <main class="app-content">
    <div class="app-title">
      <div>
        <h1><i class="fa fa-dashboard"></i> Blank Page</h1>
        <p>Start a beautiful journey here</p>
      </div>
      <ul class="app-breadcrumb breadcrumb">
        <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
        <li class="breadcrumb-item"><a href="#">Blank Page</a></li>
      </ul>
    </div>
    <div class="row">
      <div class="col-md-12">
            <a href="{{route('items.index')}}" class="btn btn-primary float-right my-2"><< Back</a>
      </div>
    </div>
    <div class="row">
      <div class="offset-md-2 col-md-8">
        <div class="tile">
          <div class="title-header">
            <h2 class="d-inline-block">Item Create</h2>
          </div>
          <form action="{{route('items.store')}}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
              <label for="name">Item Name</label>
              <input type="text" name="name" class="form-control @error('name') is-invalid @enderror" id="name" placeholder="Item Name..." value="{{old('name')}}">
              @error('name')
              <span class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
              </span>
              @enderror
            </div>
            <div class="form-group">
              <label for="photo">Photo</label>
              <input type="file" name="photo" class="form-control-file @error('photo') is-invalid @enderror" id="photo">
              @error('photo')
              <span class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
              </span>
              @enderror
            </div>
            <div class="form-group">
              <ul class="nav nav-tabs" id="myTab" role="tablist">
                <li class="nav-item" role="presentation">
                  <a class="nav-link active" id="home-tab" data-toggle="tab" href="#price" role="tab" aria-controls="home" aria-selected="true">Unit Price</a>
                </li>
                <li class="nav-item" role="presentation">
                  <a class="nav-link" id="profile-tab" data-toggle="tab" href="#discount" role="tab" aria-controls="profile" aria-selected="false">Discount Price</a>
                </li>
              </ul>
              <div class="tab-content" id="myTabContent">
                <div class="tab-pane fade show active" id="price" role="tabpanel" aria-labelledby="home-tab">
                  <input type="number" name="price" class="form-control mt-3" placeholder="Unit Price" value="{{old('price')}}">
                </div>
                <div class="tab-pane fade" id="discount" role="tabpanel" aria-labelledby="profile-tab">
                  <input type="number" name="discount" class="form-control mt-3" placeholder="Discount Price" value="{{old('discount')}}">
                </div>
              </div>
            </div>
            <div class="form-group">
              <label for="photo">Description</label>
              <textarea name="description" class="form-control @error('description') is-invalid @enderror" id="description" placeholder="Item Description..">{{old('description')}}</textarea>
              @error('description')
              <span class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
              </span>
              @enderror
            </div>
            <div class="form-group">
              <label for="name">Brand Name</label>
              <select class="form-control" name="brand_id" id="brand_id">
                <option>Choose...</option>

                @foreach ($brand as $row) {
                  <option value="{{$row->id}}">
                    {{$row->name}}
                  </option>
                }
                @endforeach
              </select>
            </div>
            <div class="form-group">
              <label for="name">SubCategories Name</label>
              <select class="form-control" name="subcategory_id" id="subcategory_id">
                <option>Choose...</option>

                @foreach ($subcategory as $row) {
                  <option value="{{$row->id}}">
                    {{$row->name}}
                  </option>
                }
                @endforeach
              </select>
            </div>
            <input type="submit" name="btnsubmit" value="Save" class="btn btn-success btn-block">
          </form>
        </div>
      </div>
    </div>
  </main>
@endsection

resources/views/backend/item/edit.blade.php
@extends('backendtemplate')

@section('content')
  <main class="app-content">
    <div class="app-title">
      <div>
        <h1><i class="fa fa-dashboard"></i> Blank Page</h1>
        <p>Start a beautiful journey here</p>
      </div>
      <ul class="app-breadcrumb breadcrumb">
        <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
        <li class="breadcrumb-item"><a href="#">Blank Page</a></li>
      </ul>
    </div>
    <div class="row">
      <div class="col-md-12">
            <a href="{{route('items.index')}}" class="btn btn-primary float-right my-2"><< Back</a>
      </div>
    </div>
    <div class="row">
      <div class="offset-md-2 col-md-8">
        <div class="tile">
          <div class="title-header">
            <h2 class="d-inline-block">Item Create</h2>
          </div>
          <form action="{{route('items.update',$item->id)}}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="form-group">
              <label for="name">Item Name</label>
              <input type="text" name="name" id="name" class="form-control @error('name') is-invalid @enderror" value="@error('name') {{old('name')}} @else {{$item->name}} @enderror" required>
              @error('name')
              <span  class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
              </span>
              @enderror
            </div>
            <div class="form-group">
              <label for="photo">Photo</label>
              <input type="file" name="photo" id="photo" class="form-control-file" accept="image/*" value="{{old('photo')}}" required>
              <img src="{{asset($item->photo)}}" width="150" height="150" class="my-1">
            </div>
            <div class="form-group">
              <ul class="nav nav-tabs" id="myTab" role="tablist">
                <li class="nav-item" role="presentation">
                  <a class="nav-link active" id="home-tab" data-toggle="tab" href="#price" role="tab" aria-controls="home" aria-selected="true">Unit Price</a>
                </li>
                <li class="nav-item" role="presentation">
                  <a class="nav-link" id="profile-tab" data-toggle="tab" href="#discount" role="tab" aria-controls="profile" aria-selected="false">Discount Price</a>
                </li>
              </ul>
              <div class="tab-content" id="myTabContent">
                <div class="tab-pane fade show active" id="price" role="tabpanel" aria-labelledby="home-tab">
                  <input type="number" name="price" class="form-control mt-3" placeholder="Unit Price" value="{{$item->price}}">
                </div>
                <div class="tab-pane fade" id="discount" role="tabpanel" aria-labelledby="profile-tab">
                  <input type="number" name="discount" class="form-control mt-3" placeholder="Discount Price" value="{{$item->discount}}">
                </div>
              </div>
            </div>
            <div class="form-group">
              <label for="photo">Description</label>
              <textarea class="form-control" name="description">{{$item->description}}</textarea>
            </div>
            <div class="form-group">
              <label for="name">Brand Name</label>
              <select class="form-control" name="brand_id" id="brand_id">
                @foreach ($brand as $row) {
                  <option value="{{$row->id}}" {{$item->brand_id==$row->id?'selected':''}}>
                    {{$row->name}}
                  </option>
                }
                @endforeach
              </select>
            </div>
            <div class="form-group">
              <label for="name">SubCategories Name</label>
              <select class="form-control" name="subcategory_id" id="subcategory_id">
                @foreach ($subcategory as $row) {
                  <option value="{{$row->id}}" {{$item->subcategory_id==$row->id?'selected':''}}>
                    {{$row->name}}
                  </option>
                }
                @endforeach
              </select>
            </div>
            <input type="submit" name="btnsubmit" value="Save" class="btn btn-success btn-block">
          </form>
        </div>
      </div>
    </div>
  </main>
@endsection

resources/views/backend/item/index.blade.php
@extends('backendtemplate')

@section('content')
  <main class="app-content">
    <div class="app-title">
      <div>
        <h1><i class="fa fa-dashboard"></i> Blank Page</h1>
        <p>Start a beautiful journey here</p>
      </div>
      <ul class="app-breadcrumb breadcrumb">
        <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
        <li class="breadcrumb-item"><a href="#">Blank Page</a></li>
      </ul>
    </div>
    <div class="row">
      <div class="col-md-12">
            <a href="{{route('items.create')}}" class="btn btn-primary float-right my-2">Add New</a>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="tile">
          <div class="title-header">
            <h2 class="d-inline-block">Items List</h2>
          </div>          
          <table class="table table-bordered dataTable">
            <thead>
              <tr>
                <th>No</th>
                <th>CodeNo</th>
                <th>Name</th>
                <th>Price</th>
                <th>Brand Name</th>
                <th>Subategory Name</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              @php
              $i=1;
              @endphp
              @foreach($item as $row)
              <tr>
                <td>{{$i++}}</td>
                <td>{{$row->codeno}}</td>
                <td>{{$row->name}}</td>
                <td>{{number_format($row->price)}}</td>
                <td>{{$row->brand->name}}</td>
                <td>{{$row->subcategory->name}}</td>
                <td>
                  <a href="{{route('items.show',$row->id)}}" class="btn btn-primary btn-sm">Detail</a>
                  <a href="{{route('items.edit',$row->id)}}" class="btn btn-warning btn-sm">Edit</a>
                  <form method="post" action="{{route('items.destroy',$row->id)}}" onsubmit="return confirm('Are you sure')" class="d-inline-block">
                    @csrf
                    @method('DELETE')
                    <input type="submit" name="btnsubmit" class="btn btn-danger btn-sm" value="Delete">
                  </form>                  
                </td>
              </tr>
              @endforeach
            </tbody>
          </table>
        
        </div>
      </div>
    </div>
  </main>
@endsection

@section('script')
  <script type="text/javascript" src="{{ asset('backend_asset/js/plugins/jquery.dataTables.min.js')}}"></script>
  <script type="text/javascript" src="{{ asset('backend_asset/js/plugins/dataTables.bootstrap.min.js')}}"></script>
  <script type="text/javascript">
    $('.dataTable').DataTable();
  </script>
@endsection

resources/views/backend/item/show.blade.php
@extends('backendtemplate')

@section('content')
  <main class="app-content">
    <div class="app-title">
      <div>
        <h1><i class="fa fa-dashboard"></i> Blank Page</h1>
        <p>Start a beautiful journey here</p>
      </div>
      <ul class="app-breadcrumb breadcrumb">
        <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
        <li class="breadcrumb-item"><a href="#">Blank Page</a></li>
      </ul>
    </div>
    <div class="row">
      <div class="col-md-12">
            <a href="{{route('items.index')}}" class="btn btn-primary float-right my-2"><< Back</a>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        {{-- <div class="tile">
          <div class="title-header">
            <h2 class="d-inline-block">Item Detail</h2>
          </div>
          <h3 class="text-primary">Name: <span class="text-dark">{{$item->name}}</span></h3>
          <h3 class="text-primary">Photo:</h3> <span><img src="{{asset('/backend_asset/images/item/'.$item->photo)}}" width="200" height="200"></span>
          <h3 class="text-primary">Price: <span class="text-dark">{{$item->price}}</span></h3>
          <h3 class="text-primary">Discount: <span class="text-dark">{{$item->discount}}</span></h3>
          <h3 class="text-primary">Description: <span class="text-dark">{{$item->description}}</span></h3>
          <h3 class="text-primary">Brand Name: <span class="text-dark">{{$item->brand->name}}</span></h3>

          <h3 class="text-primary">Subategory Name: <span class="text-dark">{{$item->subcategory->name}}</span></h3>

          

        </div> --}}
          <div class="card mb-3">
            <div class="row no-gutters">
              <div class="col-md-4">
                <img src="{{asset($item->photo)}}" class="card-img" alt="...">
              </div>
              <div class="col-md-8">
                <div class="card-body">
                  <h5 class="card-title">{{$item->name}} ({{$item->codeno}})</h5>
                  <p class="card-text">{{number_format($item->price)}} MMK</p>
                  <p class="card-text">{{$item->brand->name}}</p>
                  <p class="card-text">{{$item->subcategory->name}}</p>
                  <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
                </div>
              </div>
            </div>
          </div>
      </div>
    </div>
  </main>
@endsection